version: "3"
services:
 react-app: 
   image: react-app
   ports:
    - "3000: 3000"
 api-server: 
    image: api-server
    ports:
      -  "5000: 5000"
    depends on:
      - nongo
 auth-server: 
    image: auth-server
    ports:
      -  "5001: 5001"
    depends on:
      - nongo

nongo:
  image:  nongo:3.6.19-xenia!
  ports:
    - "27017:27017"

  valumes:
   nongo-data:
     driver: local
